### ISSUE TITLE
Feature Request: Interval command line argument

### ISSUE THREAD

**Issue by endo64** [murat-cileli/visiolog#1]
It would be nice to have an interval command line argument to change the default interval.

`visiolog capture 10`, capture every 10 seconds.

**Comment by murat-cileli** [comment]
I'm planning to implement CLI options as below:

`visiolog [positional argument] [named arguments]`

In this case, it will be:

`visiolog capture --interval 10 --ocr-languages eng,tur`

Thank you so much for your contribution.
